### PR TITLE
apache/drynx: rm cas login

### PR DESCRIPTION
**Pull request by tharvik**
Advance c4dt/TODO#210.

I'm having an issue deploying it, on `docker-compose up -d`, it fails with
```
ERROR: for traefik  Cannot create container for service traefik: Conflict. The container name "/traefik" is already in use by container "b4ba4324aede9baa15d301adeb96ec541c2e27531bc7a06ebf68a51eac7125ba". You have to remove (or rename) that container to be able to reuse that name.
ERROR: for apache  Cannot create container for service apache: Conflict. The container name "/apache" is already in use by container "07da18f5d5f01e11854648f568f18ca9497c01910ca1d90c52dfb3f25e6877d6". You have to remove (or rename) that container to be able to reuse that name.
ERROR: for socket-proxy  Cannot create container for service socket-proxy: Conflict. The container name "/socket-proxy" is already in use by container "3bbc8742ffacc0b35f0dac8faf381875bdc474c155733a6dfc489b66160390ec". You have to remove (or rename) that container to be able to reuse that name.
ERROR: for traefik  Cannot create container for service traefik: Conflict. The container name "/traefik" is already in use by container "b4ba4324aede9baa15d301adeb96ec541c2e27531bc7a06ebf68a51eac7125ba". You have to remove (or rename) that container to be able to reuse that name.
```
Note that `docker-compose ps` gives no results.

As there was some recent changes related to server management (ansible), maybe that's not the way to update it anymore? WDYT @cgrigis?

### CODE REVIEW

**Comment by cgrigis** [comment]
Correct, changes should be done in the https://github.com/c4dt/ansible-config repository, and deployed with Ansible...
Perhaps I can do a quick tutorial at the next Engineer's meeting?

Regarding the errors with `docker-compose`, they are due to the fact that Ansible now deploys the `traefik` config directly in `/home/traefik` (as opposed to the `traefik-docker` subdirectory).

**Comment by cgrigis** [comment]
@tharvik If you need to quickly make the change now, you can just do it it the `/home/traefik/Apache/700-demo.conf` and restart the compose. We can work on the Ansible part later. :)

**Comment by tharvik** [comment]
> Correct, changes should be done in the https://github.com/c4dt/ansible-config repository, and deployed with Ansible...

Ho, I though that ansible was actually pulling from this repo. If I understand you correctly, then we can archive/remove this repository, right?

> Perhaps I can do a quick tutorial at the next Engineer's meeting?

Good idea! I see a bunch of files in `playbooks/roles/traefik` and don't know most of theses.

> If you need to quickly make the change now, you can just do it it the `/home/traefik/Apache/700-demo.conf` and restart the compose. We can work on the Ansible part later. :)

Hum, it seems that the changes are already there, but it is strangely not applied. In `handlers/main.yml:Restart apache`, shouldn't you add a `build: yes` to build it when files are changed?

**Comment by cgrigis** [comment]
> Ho, I though that ansible was actually pulling from this repo. If I understand you correctly, then we can archive/remove this repository, right?

No, it was easier for Ansible to handle this directly (in a much cleaner way actually :-) ). I forgot to mark this obsolete, sorry about that...
I just added a note in the README and archived the repo.

> Good idea! I see a bunch of files in `playbooks/roles/traefik` and don't know most of theses.

:+1: 

> Hum, it seems that the changes are already there

Right, now that I remember, the changes are already there, because I took them from `c4dtsrv1` (they had been done locally and not committed).

> , but it is strangely not applied. In `handlers/main.yml:Restart apache`, shouldn't you add a `build: yes` to build it when files are changed?

Well spotted! Actually, I had tried to handle this with versioning, and there is a `docker_image` step in `tasks/main.yml` that builds the latest tag. But I forgot to bump it when I changed the contents :-P  Fixed now.

**Pull request closed without merging**
